spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    url: jdbc:postgresql://postgres_con:5432/LabXpert1
    username: postgres
    password: 123456

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 51cf9a8d55d606960466
            clientSecret: f360783f656d493d110deb5022b2c4f69f6df6be

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

logging:
  level:
    org.springframework: DEBUG

server:
  port: 8081

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
